import '../models/tube_model.dart';

enum SolveOutcome { solved, unsolvable, searchLimitReached }

class SolveReport {
  const SolveReport({
    required this.outcome,
    required this.statesExplored,
    this.pours,
  });

  final SolveOutcome outcome;

  /// Shortest number of pours that finishes the board, only set when solved.
  final int? pours;
  final int statesExplored;

  bool get isSolvable => outcome == SolveOutcome.solved;

  /// The search could not prove either way, so the caller must fall back to
  /// whatever it already knew about the position.
  bool get isConclusive => outcome != SolveOutcome.searchLimitReached;

  @override
  String toString() =>
      'SolveReport($outcome, pours: $pours, explored: $statesExplored)';
}

/// Breadth-first solver for a water-sort board.
///
/// Tube order never matters to the puzzle, so states are canonicalised by
/// sorting their tubes before they hit the visited set. That single step is
/// what keeps a 10+ colour board inside a usable node budget.
class WaterSortSolver {
  /// Levels are generated by undoing legal pours, so anything the budget cannot
  /// prove is still assumed winnable rather than thrown away.
  static const int defaultNodeBudget = 60000;

  static SolveReport solve(
    List<Tube> tubes, {
    int nodeBudget = defaultNodeBudget,
  }) => _search(
    // Every gameplay tube shares a capacity, so the first one defines it.
    _State._(
      tubes.isEmpty ? 4 : tubes.first.capacity,
      [
        for (final tube in tubes)
          [for (final color in tube.colors) color.toARGB32()],
      ],
    ),
    nodeBudget,
  );

  /// The same search over a board spelled in any layer type.
  ///
  /// The game solves painted colours and `tools/content` solves the colour ids a
  /// level file carries, and both go through this one method, so a par move
  /// count can never mean something different from the moves a player makes.
  static SolveReport solveLayers<T>(
    List<List<T>> tubes, {
    required int capacity,
    int nodeBudget = defaultNodeBudget,
  }) => _search(
    _State<T>._(capacity, [for (final tube in tubes) List<T>.of(tube)]),
    nodeBudget,
  );

  static SolveReport _search<T>(_State<T> start, int nodeBudget) {
    if (start.isSolved) {
      return SolveReport(
        outcome: SolveOutcome.solved,
        statesExplored: 0,
        pours: 0,
      );
    }

    final visited = <String>{start.key};
    var frontier = <_State<T>>[start];
    var depth = 0;
    var explored = 0;

    while (frontier.isNotEmpty) {
      depth++;
      final next = <_State<T>>[];
      for (final state in frontier) {
        for (final move in state.legalMoves()) {
          final moved = state.apply(move);
          if (moved.isSolved) {
            return SolveReport(
              outcome: SolveOutcome.solved,
              statesExplored: explored,
              pours: depth,
            );
          }
          final key = moved.key;
          if (visited.add(key)) {
            next.add(moved);
            explored++;
            if (explored >= nodeBudget) {
              return SolveReport(
                outcome: SolveOutcome.searchLimitReached,
                statesExplored: explored,
              );
            }
          }
        }
      }
      frontier = next;
    }

    return SolveReport(
      outcome: SolveOutcome.unsolvable,
      statesExplored: explored,
    );
  }
}

class PourMove {
  const PourMove(this.from, this.to, this.amount);

  final int from;
  final int to;
  final int amount;
}

class _State<T> {
  _State._(this.capacity, this.tubes);

  final int capacity;
  final List<List<T>> tubes;

  String get key {
    final parts = <String>[];
    for (final tube in tubes) {
      parts.add(tube.isEmpty ? '' : tube.join(','));
    }
    parts.sort();
    return parts.join('#');
  }

  bool get isSolved {
    for (final tube in tubes) {
      if (tube.isEmpty) continue;
      if (tube.length < capacity) return false;
      final first = tube.first;
      for (final color in tube) {
        if (color != first) return false;
      }
    }
    return true;
  }

  int _topRun(int index) {
    final tube = tubes[index];
    if (tube.isEmpty) return 0;
    final color = tube.last;
    var run = 0;
    for (var i = tube.length - 1; i >= 0 && tube[i] == color; i--) {
      run++;
    }
    return run;
  }

  /// Legal pours, with the moves that cannot make progress filtered out:
  /// a finished tube, parking a uniform tube into an empty tube, and duplicate
  /// pours into interchangeable empty tubes.
  List<PourMove> legalMoves() {
    final moves = <PourMove>[];

    for (var from = 0; from < tubes.length; from++) {
      final source = tubes[from];
      if (source.isEmpty) continue;
      final run = _topRun(from);
      if (source.length == capacity && run == capacity) continue;
      final sourceIsWholeRun = source.length == run;

      var emptyTargetTaken = false;
      for (var to = 0; to < tubes.length; to++) {
        if (to == from) continue;
        final target = tubes[to];
        if (target.length >= capacity) continue;

        if (target.isEmpty) {
          if (emptyTargetTaken || sourceIsWholeRun) continue;
          emptyTargetTaken = true;
          moves.add(PourMove(from, to, run));
        } else if (target.last == source.last) {
          final room = capacity - target.length;
          moves.add(PourMove(from, to, run < room ? run : room));
        }
      }
    }
    return moves;
  }

  _State<T> apply(PourMove move) {
    final copied = _State<T>._(capacity, [
      for (final tube in tubes) List<T>.of(tube),
    ]);
    final color = copied.tubes[move.from].last;
    for (var i = 0; i < move.amount; i++) {
      copied.tubes[move.from].removeLast();
      copied.tubes[move.to].add(color);
    }
    return copied;
  }
}
